# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployInfrastructure
  jobs:
  - job: DeployWithTerraform
    steps:
    - script: terraform init
      displayName: 'Terraform init'

    - script: terraform apply  -auto-approve 
      displayName: 'Terraform apply'

    - script: az login --service-principal -u 2f78554c-91fd-424f-aade-aaa3af7cc2db  -p xOZ8Q~hAEXHCDbqK.eRXE5wJ2RRfWulnjhFg1bkB  --tenant a047dbfb-d5eb-47f3-8d21-381786ab6c80

      displayName: 'Login to Azure'
